# Generated by Django 6.0.3 on 2026-04-29 01:50

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech', models.TextField(blank=True, help_text='Pisahkan dengan koma, misal: HTML, CSS, React', null=True)),
                ('link_repository', models.URLField(blank=True, null=True)),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.projects.models.upload_project_image)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
