# Generated by Django 6.0.3 on 2026-03-19 03:17

import users_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_rename_title_user_country_user_phone_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users_app.models.upload_profile_image),
        ),
    ]
