# Generated by Django 6.0.3 on 2026-03-19 19:37

import users_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('id_credential', models.CharField(max_length=255)),
                ('url_credential', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=users_app.models.upload_certificate_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.TextField()),
            ],
        ),
    ]
