# Generated by Django 6.0.3 on 2026-03-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
