# Generated by Django 6.0.3 on 2026-03-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='skills',
            new_name='tech',
        ),
    ]
