# Generated by Django 6.0.3 on 2026-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_rename_skills_certificate_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
