# Generated by Django 6.0.3 on 2026-03-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_certificate_expiration_date_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='tech',
            new_name='skills',
        ),
    ]
