# Generated by Django 6.0.3 on 2026-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_project_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
