# Generated by Django 6.0.3 on 2026-04-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0012_certificate_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public_portfolio',
            field=models.BooleanField(default=True),
        ),
    ]
