# Generated by Django 6.0.3 on 2026-04-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0013_user_is_public_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_public_portfolio',
            field=models.BooleanField(default=False),
        ),
    ]
