# Generated by Django 6.0.3 on 2026-04-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0014_alter_user_is_public_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
