# Generated by Django 6.0.3 on 2026-04-29 01:50

import apps.certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('id_credential', models.CharField(max_length=255)),
                ('url_credential', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.certificates.models.upload_certificate_image)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.TextField()),
            ],
        ),
    ]
